# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e1381eaca85ccca364b58503cebb592c904d9c1d6f1a5b2f6de4ee02b78c2023181fe278530f15f0b3b98ac0731fabd024ee7c9414da9a65329eccd9ac70efae

test:
  secret_key_base: 0ddb0e2400562ccf0c9dade3c8de295b716435966ede97aca594e216126519547d5de1c9a2a9555eeda75268ce89feac277e15888929527aadcdcbe755b8e12f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
